"use strict";
let count = 0;
count++;
console.log("increament by 1:", count);
let remainingItem = 10;
remainingItem--;
console.log("decreament by 1:", remainingItem);
let gameLevels = 0;
gameLevels++;
console.log("increament by 1:", gameLevels);
let noOfLives = 5;
noOfLives--;
console.log("decreament by 1:", noOfLives);
